export const ethnicityOptions = [
  "American Indian or Alaska Native",
  "Asian",
  "Black or African American",
  "Middle Eastern or North African",
  "Native Hawaiian or Other Pacific Islander",
  "White",
  "Prefer not to say",
] as const;
export const ethnicSubgroupOptions = [
  "Chinese",
  "Japanese",
  "Filipino",
  "Korean",
  "Vietnamese",
  "Asian Indian",
  "Laotian",
  "Cambodian",
  "Thai",
  "Other",
] as const;
export const genderOptions = [
  "Male",
  "Female",
  "Non-binary",
  "Prefer not to say",
] as const;
export const gradeLevelOptions = [
  "Grade 3",
  "Grade 4",
  "Grade 5",
] as const;
export const primaryInterestOptions = [
  "Entertainment",
  "Sports and Leisure",
  "Wildlife and Nature",
] as const;
export const labelTree = {
  Entertainment: {
    "Animals, Nature & Science": ["Sea Life", "Space & Light"],
    "Sports, Games & Hobbies": ["Holidays & Celebrations", "Individual Sports", "Travel & Places", "Tricks & Talents", "Video & Digital Games", "Water & Adventure"],
    "Stories & Media": ["Books & Braille", "Books & Reading", "Everyday Life & Culture", "Fairy & Folk Tales", "Famous People & Creators", "General Media", "Holidays & Celebrations", "Internet & Creators", "Movies & TV & Characters", "Music & Performing Arts"],
  },
  "Sports and Leisure": {
    "Animals, Nature & Science": ["Pets & Pet Care"],
    "Sports, Games & Hobbies": ["Crafts & Making", "General Sports & Hobbies", "Individual Sports", "Outdoor Recreation", "Team & Target Sports", "Travel & Places", "Tricks & Talents", "Video & Digital Games", "Water & Adventure"],
    "Stories & Media": ["Fairy & Folk Tales"],
  },
  "Wildlife and Nature": {
    "Animals, Nature & Science": ["General Nature & Science", "Human Body & Health", "Pets & Pet Care", "Plants & Trees", "Science & Technology", "Sea Life", "Space & Light", "Wild Animals"],
    "Sports, Games & Hobbies": ["Holidays & Celebrations"],
    "Stories & Media": ["Internet & Creators"],
  },
} as const;

export type PrimaryInterest = typeof primaryInterestOptions[number];

export const getMainLabels = (interest: PrimaryInterest) =>
  Object.keys(labelTree[interest]) as (keyof (typeof labelTree)[PrimaryInterest])[];

export const getSubLabels = (
  interest: PrimaryInterest,
  mainlabel: string
): readonly string[] => {
  const bucket = (labelTree as any)[interest]?.[mainlabel];
  return (bucket ?? []) as readonly string[];
};

export const birthPlace = [
  "United States",
  "Outside of the United States",
] as const;
export const regionOptions = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "DC",
  "AS",
  "GU",
  "MP",
  "PR",
  "VI",
] as const;
export const familyBackgroundOptions = ["Yes", "No", "I'm not sure"] as const;
export const languages = [
  "English",
  "Spanish",
  "Mandarin",
  "Cantonese",
  "French",
  "Arabic",
  "Tagalog",
  "Vietnamese",
  "Korean",
  "German",
  "Russian",
  "Hindi",
  "Portuguese",
  "Italian",
  "Japanese",
  "Other (please specify)",
] as const;
export const region = [
  "AL",
  "AK",
  "AZ",
  "AR",
  "CA",
  "CO",
  "CT",
  "DE",
  "FL",
  "GA",
  "HI",
  "ID",
  "IL",
  "IN",
  "IA",
  "KS",
  "KY",
  "LA",
  "ME",
  "MD",
  "MA",
  "MI",
  "MN",
  "MS",
  "MO",
  "MT",
  "NE",
  "NV",
  "NH",
  "NJ",
  "NM",
  "NY",
  "NC",
  "ND",
  "OH",
  "OK",
  "OR",
  "PA",
  "RI",
  "SC",
  "SD",
  "TN",
  "TX",
  "UT",
  "VT",
  "VA",
  "WA",
  "WV",
  "WI",
  "WY",
  "DC",
  "AS",
  "GU",
  "MP",
  "PR",
  "VI",
] as const;
export const vision = [
  "I don’t have a visual impairment",
  "I am Blind",
  "I have low vision",
] as const;
export const preferredMedia = [
  "Print",
  "Large Print",
  "Braille",
  "Audio",
] as const;
export const appAccess = [
  "Laptop/Computer",
  "Tablet",
  "Smart-phone",
  "Braille Note-taker",
  "Other (please specify)",
] as const;
export const digitalTextAccess = [
  "A Screen Reader",
  "A Screen Magnifier",
  "Refreshable Braille Display",
  "Other (please specify)",
] as const;
