name: Frontend Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Frontend Checks
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Adjust this to match your project's Node.js version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run ESLint
      - name: Linting
        if: always()
        run: npm run lint

      # Step 5: Check formatting
      - name: Formatting
        if: always()
        run: npm run check:formatting

      # Step 6: Type-checking (if TypeScript is being used)
      - name: Types
        if: always()
        run: npm run check:types
